apiVersion: v1
data:
  password: aVhDTVI3dDJXWExBczBpbGRMTnAzRHNFZXhncEZ0QlFVeEpKVllOdFdpNVFFRm1jSkhrcHVZSlNsRUhpaWMyWg==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: postgres.acid-minimal-cluster.credentials
  namespace: default
