apiVersion: v1
kind: Pod
metadata:
  name: dair-django
  labels:
    app: dair-django-api
spec:
  containers:
  - name: dair-django
    image: localhost:32000/django_be:latest
    command:
    - bash 
    - -c
    - "python manage.py runserver 0.0.0.0:8000"

---

apiVersion: v1
kind: Service
metadata:
  name: dair-django-service
spec:
  type: NodePort
  selector:
    app: dair-django-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008
