apiVersion: skaffold/v2beta8
kind: Config
build:
  local:
    push: true
    useDockerCLI: true
  artifacts:
      - image: localhost:32000/django_be_pg
deploy:
  kubectl:
    manifests:
      - k8s-*

